const POLL_INTERVAL = 30 // seconds
const HOST = '0.0.0.0'
const PORT = 3001
const SOCKETIO_STREAM_INFO_ROOM = 'streamInfo'
const MAX_CHAT_MESSAGE_LENGTH = 512
const NOTIFIER_IGNORE_PATTERN = '__TEST__'

export {
  HOST,
  MAX_CHAT_MESSAGE_LENGTH,
  NOTIFIER_IGNORE_PATTERN,
  POLL_INTERVAL,
  PORT,
  SOCKETIO_STREAM_INFO_ROOM,
}
